-- Create ENUM types
CREATE TYPE "public"."payment_period" AS ENUM (
    'monthly',
    'yearly',
    'lifetime'
);

CREATE TYPE "public"."type" AS ENUM (
    'starter',
    'pro',
    'trial'
);

-- Create site table
CREATE TABLE "public"."site" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "name" text NOT NULL,
    "user_id" uuid REFERENCES auth.users(id),
    "stripe_customer_id" text
);

-- Create feedback_summary table
CREATE TABLE "public"."feedback_summary" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "summary" text NOT NULL,
    "site_id" uuid REFERENCES public.site(id)
);

-- Create feedback table
CREATE TABLE "public"."feedback" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "customer_email" text,
    "feedback_text" text NOT NULL,
    "site_id" uuid REFERENCES public.site(id),
    "feedback_summary_id" bigint REFERENCES public.feedback_summary(id)
);

-- Create subscription table
CREATE TABLE "public"."subscription" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "type" "public"."type" NOT NULL,
    "payment_period" "public"."payment_period" NOT NULL,
    "monthly_usage" integer NOT NULL DEFAULT 0,
    "last_payment" timestamp with time zone,
    "site_id" uuid UNIQUE REFERENCES public.site(id)
);
